
export const NFIRS_INCIDENT_TYPES = [
    // 100 Series (Fire)
    { category_code: '100', category_description: 'Fire', code: '111', description: 'Building Fire' },
    { category_code: '100', category_description: 'Fire', code: '112', description: 'Fires in structures other than in a building' },
    { category_code: '100', category_description: 'Fire', code: '113', description: 'Cooking fire, confined to container' },
    { category_code: '100', category_description: 'Fire', code: '114', description: 'Chimney or flue fire, confined to chimney or flue' },
    { category_code: '100', category_description: 'Fire', code: '115', description: 'Incinerator overload or malfunction, fire confined' },
    { category_code: '100', category_description: 'Fire', code: '116', description: 'Fuel burner/boiler malfunction, fire confined' },
    { category_code: '100', category_description: 'Fire', code: '117', description: 'Commercial compactor fire, confined to rubbish' },
    { category_code: '100', category_description: 'Fire', code: '118', description: 'Trash or rubbish fire in a structure' },
    { category_code: '100', category_description: 'Fire', code: '121', description: 'Fire in mobile home used as a fixed residence' },
    { category_code: '100', category_description: 'Fire', code: '122', description: 'Fire in motor home, camper, recreational vehicle' },
    { category_code: '100', category_description: 'Fire', code: '123', description: 'Fire in portable building, fixed location' },
    { category_code: '100', category_description: 'Fire', code: '131', description: 'Passenger vehicle fire' },
    { category_code: '100', category_description: 'Fire', code: '132', description: 'Road freight or transport vehicle fire' },
    { category_code: '100', category_description: 'Fire', code: '133', description: 'Rail Vehicle Fire' },
    { category_code: '100', category_description: 'Fire', code: '134', description: 'Water Vehicle Fire' },
    { category_code: '100', category_description: 'Fire', code: '135', description: 'Aircraft Fire' },
    { category_code: '100', category_description: 'Fire', code: '136', description: 'Self-propelled Motor Home or Recreational Vehicle' },
    { category_code: '100', category_description: 'Fire', code: '137', description: 'Camper or Recreational Vehicle (RV) Fire' },
    { category_code: '100', category_description: 'Fire', code: '138', description: 'Off-road Vehicle or Heavy Equipment Fire' },
    { category_code: '100', category_description: 'Fire', code: '140', description: 'Natural Vegetation Fire - Other' },
    { category_code: '100', category_description: 'Fire', code: '141', description: 'Forest, Woods or Wildland Fire' },
    { category_code: '100', category_description: 'Fire', code: '142', description: 'Brush or Brush-and-Grass Mixture Fire' },
    { category_code: '100', category_description: 'Fire', code: '143', description: 'Grass Fire' },
    { category_code: '100', category_description: 'Fire', code: '150', description: 'Outside Rubbish Fire - Other' },
    { category_code: '100', category_description: 'Fire', code: '151', description: 'Outside Rubbish, Trash or Waste Fire' },
    { category_code: '100', category_description: 'Fire', code: '152', description: 'Garbage Dump or Sanitary Landfill Fire' },
    { category_code: '100', category_description: 'Fire', code: '153', description: 'Construction or Demolition Landfill Fire' },
    { category_code: '100', category_description: 'Fire', code: '154', description: 'Dumpster or Other Outside Trash Receptacle Fire' },
    { category_code: '100', category_description: 'Fire', code: '155', description: 'Outside Stationary Compactor/Compacted Trash Fire' },
    { category_code: '100', category_description: 'Fire', code: '160', description: 'Special Outside Fire - Other' },
    { category_code: '100', category_description: 'Fire', code: '161', description: 'Outside Storage Fire' },
    { category_code: '100', category_description: 'Fire', code: '162', description: 'Outside Equipment Fire' },
    { category_code: '100', category_description: 'Fire', code: '163', description: 'Outside Gas or Vapor Combustion Explosion' },
    { category_code: '100', category_description: 'Fire', code: '164', description: 'Outside Mailbox Fire' },
    { category_code: '100', category_description: 'Fire', code: '170', description: 'Cultivated Vegetation, Crop Fire - Other' },
    { category_code: '100', category_description: 'Fire', code: '171', description: 'Cultivated Grain or Crop Fire' },
    { category_code: '100', category_description: 'Fire', code: '172', description: 'Cultivated Orchard or Vineyard Fire' },
    { category_code: '100', category_description: 'Fire', code: '173', description: 'Cultivated Trees or Nursery Stock Fire' },
    // 200 Series
    { category_code: '200', category_description: 'Overpressure Explosion, Rupture, Overheat (no fire)', code: '211', description: 'Overpressure rupture of steam pipe/pipeline' },
    { category_code: '200', category_description: 'Overpressure Explosion, Rupture, Overheat (no fire)', code: '251', description: 'Excessive heat, scorch burns with no ignition' },
    // 300 Series
    { category_code: '300', category_description: 'Rescue & EMS Incidents', code: '311', description: 'Medical assist, assist EMS crew' },
    { category_code: '300', category_description: 'Rescue & EMS Incidents', code: '321', description: 'EMS call, excluding vehicle accident with injury' },
    { category_code: '300', category_description: 'Rescue & EMS Incidents', code: '322', description: 'Motor Vehicle Accident with injuries' },
    { category_code: '300', category_description: 'Rescue & EMS Incidents', code: '323', description: 'Motor vehicle/pedestrian accident (MV Ped)' },
    { category_code: '300', category_description: 'Rescue & EMS Incidents', code: '324', description: 'Motor vehicle accident with no injuries' },
    { category_code: '300', category_description: 'Rescue & EMS Incidents', code: '352', description: 'Extrication of victim(s) from vehicle' },
    // 400 Series
    { category_code: '400', category_description: 'Hazardous Condition (No Fire)', code: '411', description: 'Gasoline or other flammable liquid spill' },
    { category_code: '400', category_description: 'Hazardous Condition (No Fire)', code: '412', description: 'Gas leak (natural gas or LPG)' },
    { category_code: '400', category_description: 'Hazardous Condition (No Fire)', code: '422', description: 'Chemical spill or leak' },
    { category_code: '400', category_description: 'Hazardous Condition (No Fire)', code: '444', description: 'Power line down' },
    // 500 Series
    { category_code: '500', category_description: 'Service Call', code: '511', description: 'Lock-out' },
    { category_code: '500', category_description: 'Service Call', code: '522', description: 'Water or steam leak' },
    { category_code: '500', category_description: 'Service Call', code: '551', description: 'Assist police or other governmental agency' },
    { category_code: '500', category_description: 'Service Call', code: '561', description: 'Unauthorized burning' },
    // 600 Series
    { category_code: '600', category_description: 'Good Intent Call', code: '611', description: 'Dispatched & canceled en route' },
    { category_code: '600', category_description: 'Good Intent Call', code: '622', description: 'No incident found on arrival at dispatch address' },
    { category_code: '600', category_description: 'Good Intent Call', code: '631', description: 'Authorized controlled burning' },
    { category_code: '600', category_description: 'Good Intent Call', code: '651', description: 'Smoke scare, odor of smoke' },
    // 700 Series
    { category_code: '700', category_description: 'False Alarm & False Call', code: '735', description: 'Alarm system sounded due to malfunction' },
    { category_code: '700', category_description: 'False Alarm & False Call', code: '743', description: 'Smoke detector activation, no fire - unintentional' },
    { category_code: '700', category_description: 'False Alarm & False Call', code: '745', description: 'Alarm system activation, no fire - unintentional' },
    // And so on for all types...
];
